version: '3.3'

services:
  spring-api1:
    container_name: api1
    build: .
    hostname: spring-api1
    environment:
      - DATABASE_URL=database
    depends_on:
      - db-mongo
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'
    networks:
      - app-network
  spring-api2:
    container_name: api2
    build: .
    hostname: spring-api2
    environment:
      - DATABASE_URL=database
    depends_on:
      - db-mongo
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.25GB'
  db-mongo:
    image: mongo
    container_name: mongo_rinha
    command: [ --auth ]
    restart: always
    hostname: database
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: rinha
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    networks:
      - app-network
networks:
  app-network: